# Generated by Django 5.1.2 on 2024-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedload_app', '0002_alter_section_link_alter_section_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/'),
        ),
    ]
