# Generated by Django 5.1.2 on 2024-10-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedload_app', '0003_section_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
