# Generated by Django 5.1.2 on 2024-10-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedload_app', '0004_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='icon',
            field=models.CharField(choices=[('fas fa-home', 'خانه'), ('fas fa-info', 'درباره ما'), ('fas fa-envelope', 'تماس با ما'), ('fas fa-cog', 'تنظیمات'), ('fas fa-users', 'کاربران')], max_length=50),
        ),
    ]
