# Generated by Django 5.1.2 on 2024-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedload_app', '0005_alter_sidebar_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='icon',
            field=models.ImageField(upload_to='sidebar_icons/'),
        ),
    ]
